### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sjthespian** [ganglia/chef-ganglia#74]
Version 0.2.3 was released back in 2014 and there has been quite a bit of development on this cookbook since that time. Any chance of a 0.2.4 release?

The biggest thing I need is the package support on Centos and Redhat, we don't want to have to build from source every time we install gmond on a host.

**Comment by lexvector** [comment]
I'd like to second this request for package support to be added with release 0.2.4.

**Comment by lexvector** [comment]
Until the 0.2.4 release is made to supermarket.getchef.com , for testing in a ChefDK environment one  can change the Berksfile to include this line, and it will pull the 0.2.4 release

cookbook "ganglia", git: "https://github.com/ganglia/chef-ganglia"

**Comment by brianudwa** [comment]
I'd like to 3rd the request for bumping this to 0.2.4 along with package support. The current version of 0.2.3 does not work well with a system designed for configuration management as one of the points of configuration management is to avoid drift among systems and having nodes with hand compiled binaries laying around (regardless of whether is is a cookbook that compiles them) is messy from a debugging standpoint, because what compiles one way on a system isn't necessarily the same on another as different classes of machines could have different libraries installed.

**Comment by maplebed** [comment]
sorry it took so long. current state of master is now live on supermarket.
